export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_POST = 'GET_ALL_POST';
export const GET_POST_CATEGORIAS = 'GET_POST_CATEGORIAS';
export const GET_ALL_CATEGORIAS = 'GET_ALL_CATEGORIAS';
export const POST_CATEGORIAS = 'POST_CATEGORIAS';
